" Plugin section

" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'arcticicestudio/nord-vim'


" Allows sending text to other windows
Plug 'jpalardy/vim-slime'


Plug 'lervag/vimtex'

" YouCompleteMe
Plug 'Valloric/YouCompleteMe'


" Track the engine.
Plug 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plug 'honza/vim-snippets'

call plug#end()

" Colors section
colorscheme nord


" Settings
set nocompatible
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on
set encoding=utf-8
set number
set relativenumber
set splitright

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab


" Define where slime sends output
let g:slime_target = "vimterminal"

" Define leader key
let mapleader= ","
let maplocalleader= "-"


" Latex setup
let g:vimtex_view_method = 'zathura'
let g:livepreview_previewer = 'zathura'
"let g:ale_completion_enabled = 1
let g:ale_linters_explicit = 1

set conceallevel=1
let g:tex_conceal='abdmg'
" Set default latex type
let g:tex_flavor = "latex"
" Disable warnings about missing clientserver, since none is available
let g:vimtex_compiler_latexmk = {'callback' : 0}

" Remaps
nnoremap tk  :tabnext<CR>
nnoremap tj  :tabprev<CR>
noremap  tn  :tabnew<CR>
nnoremap  <leader>q   :Explore<CR>



" Split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>


" Ultisnips
let g:UltiSnipsSnippetsDir = "~/.vim/myUltiSnips"
let g:UltiSnipsSnippetDirectories=["UltiSnips", "myUltiSnips"]
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger='<leader>e'
let g:UltiSnipsJumpForwardTrigger='<c-j>'
let g:UltiSnipsJumpBackwardTrigger='<c-k>'

" Screenshot
 let @s=':read! screenshot.sh %'
" Leader commands




